import type { ModelArchitecture } from "./schema";

export interface RenderedGraph { readonly svg: string; readonly height: number }
export type ArchitectureRender = (view: string, mode: string, width: number) => RenderedGraph;
const escape = (value: string): string => value.replace(/[&<>"']/g, (ch) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[ch]!);

/** Static SVG and full native disclosures remain readable with JavaScript disabled. */
export function renderArchitectureDocument(model: ModelArchitecture, render: ArchitectureRender): string {
  const overview = render("model", "inference", 720);
  const payload = JSON.stringify(model).replace(/</g, "\\u003c").replace(/\u2028/g, "\\u2028").replace(/\u2029/g, "\\u2029");
  const sources = model.sources.map((source, index) => `<li><a href="${escape(source.href)}" target="_blank" rel="noopener noreferrer">[${index + 1}] ${escape(source.label)}</a> — ${escape(source.note)}</li>`).join("");
  const fallback = model.views.map((view) => `<details class="atlas-static-view"><summary>${escape(view.label)} · ${escape(view.title)}</summary><p>${escape(view.description)}</p>${view.id === "model" ? "" : `<div class="atlas-static-diagram">${render(view.id, "inference", 720).svg}</div>`}<ol>${view.nodes.map((node) => `<li><strong>${escape(node.title)}</strong> <small>(${escape(node.evidence)})</small><p>${escape(node.description)}</p><code>${escape(node.operation)}</code><p>Input: ${escape(node.input)}<br>Output: ${escape(node.output)}</p>${node.cost ? `<p>${escape(node.cost)}</p>` : ""}<p>Sources: ${node.references.map((index) => `<a href="${escape(model.sources[index].href)}" target="_blank" rel="noopener">[${index + 1}] ${escape(model.sources[index].label)}</a>`).join(", ")}</p></li>`).join("")}</ol></details>`).join("");
  return `<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escape(model.title)} · Architecture explorer</title><meta name="description" content="${escape(model.description)}"><link rel="stylesheet" href="./base.css"></head>
<body><main id="model-atlas" data-curated-model="${escape(model.id)}">
<header class="atlas-header"><div><div class="atlas-overline">${escape(model.family)} / ${model.views.length} VIEWS</div><h1 class="atlas-title">${escape(model.title)}</h1><p class="atlas-intro">${escape(model.description)}</p><div class="atlas-legend" aria-label="Connection legend"><span>Solid: computation</span><span>Green: cache</span><span>Dashed: control / gradients</span></div></div><button type="button" class="atlas-control atlas-export" id="atlas-export">↓ Export this SVG</button></header>
<nav class="atlas-tabs" id="atlas-tabs" aria-label="Architecture views"></nav>
<section aria-labelledby="atlas-view-title"><div class="atlas-view-header"><div class="atlas-breadcrumb" id="atlas-breadcrumb">Architecture / Model</div><h2 class="atlas-view-title" id="atlas-view-title">${escape(model.views[0].title)}</h2><p class="atlas-view-description" id="atlas-view-description">${escape(model.views[0].description)}</p></div>
<div class="atlas-toolbar" aria-label="Diagram controls"><div class="atlas-playback"><button type="button" class="atlas-control" id="atlas-previous" aria-label="Previous computation stage">← Previous</button><button type="button" class="atlas-control" id="atlas-play" aria-label="Play computation stages" aria-pressed="false">▷ Play</button><button type="button" class="atlas-control" id="atlas-next" aria-label="Next computation stage">Next →</button><span class="atlas-stage-count" id="atlas-stage-count">All stages</span><button type="button" class="atlas-link-button" id="atlas-show-all">Show all</button></div><label id="atlas-mode-label" hidden>Context<select id="atlas-mode"><option value="inference">Inference</option><option value="training">Training</option></select></label></div>
<p class="atlas-step-detail" id="atlas-step-detail" role="status" aria-live="polite">Select a component or connector to inspect the computation.</p><div class="atlas-stage" id="atlas-stage" tabindex="0" aria-label="Architecture diagram. Arrow keys step through stages; Enter inspects the focused component.">${overview.svg}</div><div class="atlas-board-caption"><span>Scroll inside the diagram on narrow screens. Select any module or connector for detail.</span><button type="button" class="atlas-link-button" id="atlas-back-controls">↑ Back to controls</button></div></section>
<section class="atlas-inspector" id="atlas-inspector" aria-labelledby="atlas-inspector-title"><div class="atlas-inspector-heading"><div><div class="atlas-overline">INSPECT / TENSORS &amp; CONNECTIONS</div><h2 class="atlas-inspector-title" id="atlas-inspector-title" tabindex="-1">Inspect the computation</h2></div></div><p>Select a component for its operation, tensor shapes, evidence and sources.</p></section>
<p class="atlas-scope" id="atlas-scope">${escape(model.scope)}</p><details class="atlas-sources"><summary>Primary sources and scope</summary><ul>${sources}</ul><p>Evidence: CODE = released implementation/configuration; PAPER = reported mechanism; DERIVED = mathematical consequence; UNKNOWN = unresolved detail; PROPOSAL = article extension. Playback walks the architecture; it does not run model inference.</p></details>
<noscript><section class="atlas-static-content" aria-label="Complete architecture details"><h2>Architecture views and component details</h2>${fallback}</section></noscript>
<span class="atlas-sr-only" id="atlas-view-scope"></span><span class="atlas-sr-only" id="atlas-announcement" role="status" aria-live="polite"></span>
</main><script src="./architecture.js"></script><script>window.ModelAtlas=window.ModelArchitecture.create(${payload});</script><script src="./controls.js"></script></body></html>`;
}
